export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const LIST_CATEGORIES_SUCCESS = 'LIST_CATEGORIES_SUCCESS';
export const LIST_CATEGORIES_FAILURE = 'LIST_CATEGORIES_FAILURE';
export const LIST_CATEGOR_PRODUCTS = 'LIST_CATEGOR_PRODUCTS';
export const LIST_CATEGOR_PRODUCTS_SUCCESS = 'LIST_CATEGOR_PRODUCTS_SUCCESS';
export const LIST_CATEGOR_PRODUCTS_FAILURE = 'LIST_CATEGOR_PRODUCTS_FAILURE';