export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS';
export const LIST_PRODUCTS_FAILURE = 'LIST_PRODUCTS_FAILURE';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const SHOW_PRODUCT_SUCCESS = 'SHOW_PRODUCT_SUCCESS';
export const SHOW_PRODUCT_FAILURE = 'SHOW_PRODUCT_FAILURE';